### ISSUE TITLE
region.json data set in legislator dataset is invalid

### ISSUE THREAD

**Issue by toytown** [awslabs/aws-serverless-data-lake-framework#28]
**Describe the bug**
region.json data set in legislator dataset is invalid

**To Reproduce**
1. Run legislators dataset 
2. Wait for few minutes
3. Check the step function sdlf-<team>-main-sm-a and the lambda associated with it . In the cloudwatch logs you will see

2021-02-17T22:19:21.385+01:00Copy[ERROR] JSONDecodeError: Extra data: line 2 column 1 (char 85)Traceback (most recent call last):  File "/var/task/lambda_function.py", line 63, in lambda_handler    raise e  File "/var/task/lambda_function.py", line 54, in lambda_handler    bucket, key, team, dataset)  # custom user code called  File "/opt/python/datalake_library/transforms/stage_a_transforms/light_transform_blueprint.py", line 62, in transform_object    json_data = json.loads(data)  File "/var/lang/lib/python3.7/json/__init__.py", line 348, in loads    return _default_decoder.decode(s)  File "/var/lang/lib/python3.7/json/decoder.py", line 340, in decode    raise JSONDecodeError("Extra data", s, end) | [ERROR] JSONDecodeError: Extra data: line 2 column 1 (char 85) Traceback (most recent call last):   File "/var/task/lambda_function.py", line 63, in lambda_handler     raise e   File "/var/task/lambda_function.py", line 54, in lambda_handler     bucket, key, team, dataset) # custom user code called   File "/opt/python/datalake_library/transforms/stage_a_transforms/light_transform_blueprint.py", line 62, in transform_object     json_data = json.loads(data)   File "/var/lang/lib/python3.7/json/__init__.py", line 348, in loads     return _default_decoder.decode(s)   File "/var/lang/lib/python3.7/json/decoder.py", line 340, in decode     raise JSONDecodeError("Extra data", s, end)

--

 

**Expected behavior**

**Screenshots**

**SDLF release (if known):**
E.g. 1.0.1.1

**Additional context**

**Comment by jaidisido** [comment]
Thanks for raising this @toytown but this is expected behavior. Four files are uploaded into S3 in the legislators example, three of them should succeed, one should fail (i.e. `regions.json`). This is intentional and used to showcase how the SDLF reacts when there is a failure (Dead-Letter queue, alarm...)
